/* tslint:disable */
/* eslint-disable */
/**
 * Honlsoft COVID-19 API
 * Data from the COVID-19 Tracking Project aggregated in different ways to support API access.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

