name: Run-Unit-Tests
on: push
jobs:
  unit-test:
    name: Run All .NET Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - run: dotnet build
      - run: dotnet test